### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by bsayed** [AtomLinter/linter-erlc#2]
[Enter steps to reproduce below:]

1. I haven't done anything except opening an erlang file

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter-erlc](https://github.com/AtomLinter/linter-erlc) package, v0.1.2

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At child_process.js:1160

Error: spawn ENOTDIR
  at exports._errnoException (util.js:742:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Users/b_sayed/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at LinterErlc.lintFile (/Users/b_sayed/.atom/packages/linter-erlc/lib/linter-erlc.coffee:58:16)
  at /Users/b_sayed/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/b_sayed/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
  3x -9:23.9 core:confirm (input.hidden-input)
     -2:11.7 core:paste (input.hidden-input)
     -2:10.6 core:confirm (input.hidden-input)
  3x -1:38.1 core:backspace (input.hidden-input)
     -1:35.2 core:confirm (input.hidden-input)
     -0:35.2 settings-view:open (input.hidden-input)
     -0:03.5 core:confirm (input.hidden-input)
 10x -0:01.2 core:backspace (input.hidden-input)
     -0:00.0 editor:consolidate-selections (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "yosemite-unity-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
elixir-cmd, v0.2.3
language-elixir, v0.3.3
language-erlang, v2.0.0
linter, v0.9.0
linter-elixirc, v0.2.1
linter-erlc, v0.1.2
minimap, v3.4.9
vim-mode, v0.22.0
yosemite-unity-ui, v0.3.13

# Dev
No dev packages
```

/cc @atom/core

**Comment by JonGretar** [comment]
This means that the `erlc` command was not found in $PATH.
Update to the latest version and set full path to `erlc` using the `Erlc Executable Path` settings.
